# Generated by Django 4.0.3 on 2022-06-23 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypBadan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80)),
                ('jednostka', models.CharField(max_length=80)),
                ('min_wart_ref', models.FloatField()),
                ('maks_wart_ref', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=80)),
                ('nazwisko', models.CharField(max_length=80)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('godzina', models.TimeField(default=django.utils.timezone.now)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.FloatField()),
                ('typBadania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wyniki', to='badania.typbadan')),
                ('zlecenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyniki', to='badania.zlecenie')),
            ],
        ),
    ]
