# Generated by Django 4.0.3 on 2022-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badania', '0003_alter_zlecenie_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='imie',
            field=models.CharField(max_length=30),
        ),
    ]
