# Generated by Django 4.0.3 on 2022-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badania', '0005_alter_typbadan_nazwa_alter_zlecenie_imie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='badanie',
            constraint=models.UniqueConstraint(fields=('typBadania', 'zlecenie'), name='badanie'),
        ),
    ]
