# Generated by Django 4.0.3 on 2022-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badania', '0006_badanie_badanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='opis',
            field=models.TextField(blank=True),
        ),
    ]
